### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by App-247** [OCA/vertical-medical#144]
Hi, I want to migrate the **medical** module to version **10.0**. Thanks.

**Comment by lasley** [comment]
Hi @App-247 - thanks for the initiative. Please see my comments in your PR and let me know if you have any questions. I would love to coordinate the upgrade effort with you; we can do so in #117.

Also a great way to contribute is to review the existing PRs. Half the reason that I haven't submitted all my v10 work yet is because my v9 work sat for nearly a year before getting reviewed.

It is incredibly difficult to maintain PRs for two modules at the same time, as evidenced by my currently open PR count & the fact that a lot of them are probably waiting on me to do some change that happened in one and not the other.
