### ISSUE TITLE
Medical Manufacturer

### ISSUE THREAD

**Issue by bealdav** [OCA/vertical-medical#153]
Hi @bmw65 and @lasley 

Good activity in this repository, nice.

Sure your modules will have nice success in a near future in all over the world.

Just one point. Your module medical_manufacturer seems to be generic, not specific to medical.

It's not a problem for me, you can let it as it. But maybe you can get less maintenance work on your side putting it this module in partner-contact or manufacture repo, don't you think ?

**Comment by lasley** [comment]
Hi @bealdav - Yeah if this is something that OCA can use outside of medical context, great! 

In v10 this module went kind of a different direction due to the Medical Abstract Entity that was introduced in #119. The current implementation relies on a`is_manufacturer` column that was starting to stack up with the other entity types. It was also somewhat conflicting with the new partner types introduced post v8 that allowed for the delivery addresses and stuff.

Do you think something like the abstract entity would also be something OCA wants? I'll be making an RFC to the partner-contact repo before moving anything over, so just wondering if I should include that as well.

[This is the v10 manufacturer implementation.](https://github.com/LasLabs/vertical-medical/tree/release/10.0/medical_manufacturer)

**Comment by bealdav** [comment]
Yes it could be a good addition to have a generic way to define specific partners base on res.partner, a type and another table to store specific fields
On my side I had to deal with dropoff.site as partner extension in v6. Abstract it could be an improvment.
If you make a PR, I'll approve it.

Thanks

**Comment by pedrobaeza** [comment]
There's a module product_manufactures that can be linked with this. Anyway, I prefer partner_custom_info to add more info to the partners in a templating way.

**Comment by lasley** [comment]
@pedrobaeza - We were actually thinking of hooking into this at the product_brand level, but that's mainly because I didn't know about the product_manufacturer module. Seems like a why not both scenario IMO.

Regarding partner_custom_info - we didn't go this direction because an explicit context is required for us. We are injecting a lot of custom methods, fields, and defaults into these models in some of the downstream modules. We use delegate inheritance to maintain the contexts. Medical Manufacturer isn't an amazing example, but that's mainly because it's a newer concept & we haven't ripped out some other things to use it. 

A better example is [patient](https://github.com/LasLabs/vertical-medical/blob/release/10.0/medical/models/medical_patient.py), which already starts with a decent set of customizations but then just gets insane by the time we've brought in something like [socioeconomics](https://github.com/LasLabs/vertical-medical/blob/release/10.0/oemedical_socioeconomics/oemedical_socioeconomics/oemedical_socioeconomics.py#L31). There's no methods there, but that's mainly because we haven't upgraded it yet.

**Comment by pedrobaeza** [comment]
OK, it's acceptable to rely on a fixed DB structure
