### ISSUE TITLE
Was this project abandoned?

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/vertical-medical#229]
I have a demand related to this project and it seems that the project has been abandoned. I saw that the legal issues were resolved but I would like to know if there is any kind of restriction that is preventing the evolution of this project or is it just a lack of manpower?

Is it possible to create branches 11.0, 12.0 and 13.0?

cc @OCA/vertical-medical-maintainers

**Comment by etobella** [comment]
Hi @marcelsavegnago The main problem of this project was related to the issue related to the License. As this was a problem, we developed it from scratch in another repo, and we didn't propose anything as there was no one interested. If you think this might be interesting, we can propose something here. Our new repo is 
https://github.com/tegin/medical-fhir
It is similar in some sense, but based on the FHIR protocol. We also have some modules linking sales and so on, but in other repos. If it is interesting for more people, we can propose them here.

**Comment by marcelsavegnago** [comment]
Hi @etobella.

I took a look at your repository and also saw the repository where you have the integration modules with sales, mgmtsystem and others. 

Very good. 👏 

I like the idea of proposing something here. I still have no real case for using these modules but I can help in some way.

**Comment by rvalyi** [comment]
wow there is an XSD schema for HL7 FHIR https://www.hl7.org/fhir/xml.html#schema
I'm pretty sure my Odoo generator can generate Odoo mixins for all the XSD types...
https://github.com/akretion/generateds-odoo
and there is more coming... Ping me if you are interested in getting this automated and 100% compliant...

**Comment by etobella** [comment]
@marcelsavegnago As soon as you have a project or real case we can start to merge here. We are currently working with this implementation on our clinic and medical centers and works perfectly :smile: We prefer to wait until someone else starts because once we share it inside the OCA it might be harder to add new features if there is no more people involved.

@rvalyi great tool!!! Sad to see that we already did all the effort manually :disappointed: However, HL7 FHIR does not require that your database fulfills that implementation exactly. For example, when you are talking about payors, practitioners or patients, they are equivalent to odoo partners, so you need to do this integration manually. Also for claims, that could correspond to sale orders or invoices.

**Comment by marcelsavegnago** [comment]
@etobella I agree. For the time being we are prospecting a possible customer and I hope the prospect will become a customer soon. In the meantime, we are testing the modules that are in your repository. Thanks for the help and for sharing.

**Comment by etobella** [comment]
Ok!!! If you need some demo from a real environment ping me:smile:

**Comment by marcelsavegnago** [comment]
> Ok!!! If you need some demo from a real environment ping me😄

Ok.. thanks 👍  👍 🍻
