### ISSUE TITLE
[new Feature] visualization of streaming data/anomaly highlighting

### ISSUE THREAD

**Issue by breznak** [OCA/vertical-medical#65]
Hello, 
I'm one of the developers of https://github.com/nupic-community/nupic.visualizations , an interactive visualization tool for streaming data, monitoring and anomaly highlighting. 
I'm wondering if the functionality could be any helpful for your project? 
Thanks for your feedback.

**Comment by lasley** [comment]
Hi @breznak - This looks like a nice project, but I'm not so sure how easy it will be to integrate into the existing ERP resources. Node is technically a requirement of Odoo, so this is possible from that standpoint, however we need more of an embedded approach IMO.

I'm going to close this ticket though - I believe this conversation would be more suited to a more centralized repo such as our [reporting-engine](https://github.com/OCA/reporting-engine) in order to target all business aspects in an abstract manor, with dependent modules being created in the relevant repo for adaptation to specific business logic. This is a pretty niche repo with pretty low activity, so buy-in for a project of this proportions will likely not happen here.

If you think it would be possible to embed this application and directly feed data to it instead of a data file, please open an issue in [reporting-engine](https://github.com/OCA/reporting-engine) so we can resume the discussion there. Node is a dependency of Odoo, so we do have the resources available from an ops perspective, but having to run an additional server might be a blocker for most of the community.
